@preconcurrency import AppKit
import Foundation

@MainActor
final class ClipboardMonitor {
    private let pasteboard: NSPasteboard
    private var task: Task<Void, Never>?
    private var lastChangeCount = 0
    private var onTextChange: ((String) -> Void)?

    private let protectedTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    func start(onTextChange: @escaping (String) -> Void) {
        stop()
        self.onTextChange = onTextChange
        lastChangeCount = pasteboard.changeCount
        task = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                try? await Task.sleep(for: .milliseconds(500))
                guard !Task.isCancelled else { return }
                self?.poll()
            }
        }
    }

    func stop() {
        task?.cancel()
        task = nil
        onTextChange = nil
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        let types = Set(pasteboard.types ?? [])
        guard protectedTypes.isDisjoint(with: types),
              let text = pasteboard.string(forType: .string)
        else { return }
        onTextChange?(text)
    }
}
